version: "3.8"
services:
  rails:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3001 -b '0.0.0.0'"
    ports:
      - 3001:3001
    volumes:
      - .:/app
      - /app/tmp
      # Gemデータの永続化
      - gem_data:/usr/local/bundle
    depends_on:
      - db
    networks:
      - nutritional-record_network
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3307:3306
    expose:
      - 3307
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - nutritional-record_network
  # swagger-ui:
  #   image: swaggerapi/swagger-ui
  #   container_name: "nutritional-record-swagger-ui"
  #   ports:
  #     - "8001:8080"
  #   volumes:
  #     - ./document/openapi.yaml:/openapi.yaml
  #   environment:
  #     SWAGGER_JSON: /openapi.yaml
  # swagger-api:
  #   image: danielgtaylor/apisprout
  #   container_name: "nutritional-record-swagger-api"
  #   ports:
  #     - "8002:8000"
  #   volumes:
  #     - ./document/openapi.yaml:/openapi.yaml
  #   entrypoint: /usr/local/bin/apisprout /openapi.yaml --watch
  #   networks:
  #     nutritional-record_network:
  #       aliases:
  #         - local.swagger.apisprout
  # swagger-api-nginx:
  #   image: nginx:mainline-alpine
  #   container_name: "nutritional-record-swagger-api-nginx"
  #   ports:
  #     - "8003:8088"
  #   volumes:
  #     - ./document/nginx/swagger.conf:/etc/nginx/conf.d/default.conf
  #   networks:
  #     nutritional-record_network:
  #       aliases:
  #         - local.swagger.api
  # swagger-watch:
  #   build: ./document/swagger-watch
  #   volumes:
  #     - ./document/swagger-watch:/app
  #     - /app/node_modules
  #     - ./document/src:/src
  #     - ./document/openapi.yaml:/docs/swagger.yml
  #   working_dir: /app
  #   command: 'node index.js'
volumes:
  db-data:
  gem_data:
networks:
  nutritional-record_network:
    external: true
